# Prometheus configuration for PNO Physics Bench
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PNO API Server metrics
  - job_name: 'pno-api'
    static_configs:
      - targets: ['pno-api:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Training job metrics (if running)
  - job_name: 'pno-training'
    static_configs:
      - targets: ['pno-gpu:8080']  # Custom metrics endpoint
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # GPU metrics (if NVIDIA GPU available)
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 30s

  # Custom ML metrics
  - job_name: 'ml-metrics'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets/ml-jobs.json'
        refresh_interval: 30s