{
  "global": {
    "scrape_interval": "15s",
    "evaluation_interval": "15s"
  },
  "rule_files": [
    "pno_rules.yml"
  ],
  "scrape_configs": [
    {
      "job_name": "pno-physics-bench",
      "kubernetes_sd_configs": [
        {
          "role": "pod"
        }
      ],
      "relabel_configs": [
        {
          "source_labels": [
            "__meta_kubernetes_pod_annotation_prometheus_io_scrape"
          ],
          "action": "keep",
          "regex": true
        },
        {
          "source_labels": [
            "__meta_kubernetes_pod_annotation_prometheus_io_path"
          ],
          "action": "replace",
          "target_label": "__metrics_path__",
          "regex": "(.+)"
        }
      ]
    }
  ],
  "alerting": {
    "alertmanagers": [
      {
        "kubernetes_sd_configs": [
          {
            "role": "pod"
          }
        ],
        "relabel_configs": [
          {
            "source_labels": [
              "__meta_kubernetes_pod_label_app"
            ],
            "action": "keep",
            "regex": "alertmanager"
          }
        ]
      }
    ]
  }
}