apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pno-role
  namespace: production
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
