env:
  IMAGE_NAME: pno-physics-bench
  REGISTRY: ghcr.io
jobs:
  build:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
    - name: Push to registry
      run: docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to staging
      run: kubectl apply -f deployment/staging/
    - name: Run integration tests
      run: python tests/integration_tests.py
    - if: success()
      name: Deploy to production
      run: kubectl apply -f deployment/production/
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: python -m pytest tests/ --cov=src --cov-report=xml
    - name: Run security scan
      run: python autonomous_quality_gates_final.py
name: PNO Physics Bench CI/CD
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - develop
